<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple Computer//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>comment</key>
	<string>ASP SCRIPTING DICTIONARY – By Rich Barton: Version 1.0 (based on PHP Scripting Dictionary by Justin French, Sune Foldager and Allan Odgaard) Note: .asp is handled by asp/html</string>
	<key>fileTypes</key>
	<array>
		<string>asa</string>
	</array>
	<key>name</key>
	<string>ASP - JScript</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>match</key>
			<string>(?i:\b(Application|ObjectContext|Request|Response|Server|Session)\b)</string>
			<key>name</key>
			<string>support.class.asp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Contents|StaticObjects|ClientCertificate|Cookies|Form|QueryString|ServerVariables)\b)</string>
			<key>name</key>
			<string>support.class.collection.asp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(TotalBytes|Buffer|CacheControl|Charset|ContentType|Expires|ExpiresAbsolute|IsClientConnected|PICS|Status|ScriptTimeout|CodePage|LCID|SessionID|Timeout)\b)</string>
			<key>name</key>
			<string>support.constant.asp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Lock|Unlock|SetAbort|SetComplete|BinaryRead|AddHeader|AppendToLog|BinaryWrite|Clear|End|Flush|Redirect|Write|CreateObject|HTMLEncode|MapPath|URLEncode|Abandon)\b)</string>
			<key>name</key>
			<string>support.function.asp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>(?i:\b(Application_OnEnd|Application_OnStart|OnTransactionAbort|OnTransactionCommit|Session_OnEnd|Session_OnStart|Class_Initialize|Class_Terminate)\b)</string>
			<key>name</key>
			<string>support.function.event.asp</string>
		</dict>
		<dict>
			<key>match</key>
			<string>\b((0(x|X)[0-9a-fA-F]*)|(([0-9]+\.?[0-9]*)|(\.[0-9]+))((e|E)(\+|-)?[0-9]+)?)(L|l|UL|ul|u|U|F|f)?\b</string>
			<key>name</key>
			<string>constant.numeric.asp</string>
		</dict>
	</array>
	<key>scopeName</key>
	<string>source.asp</string>
	<key>uuid</key>
	<string>291022B4-6B1D-11D9-90EB-000D93589AF6</string>
</dict>
</plist>
